[tool.poetry]
name = "options-trader"
version = "1.005"
description = "Options trader"
authors = ["Pablo Pe√±a <pablorpena909@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
pandas = "2.2.2"
requests = "2.31.0"
pydantic = "2.7.1"
websockets = "12.0"
schedule = "1.2.2"
